language: C++
sudo: false
os: osx
osx_image: xcode9.2

env:
  global:
  - secure: z70ZSe8gw9m+680CODuuWpTyr9jBzcsF2hlneZdYNGAKUwzWMavrZYbaxoTlDB239/GE9BAypshucft5U0G89S1oOx8TGR5fbabs7hiUU+W5LRarMuESyCSlkk6zRB0Hl1HOQaPoHEM0TOXTXjn0LF7diu7KK+f/Rafce4pZM1gbUW+kOjVgpk+m7NBg9aUrhM0PGT39pfb+ES/zgihxpfQQu9Tg0vfqwVRzamCs3+0xjX2hfEEwTK+PEgrcxUdscrdkcXqv9Ly/CYDmGGwPuyrJfkaaIQgVmPuslnDPpIYaUq2FmJtdIUT6AnrMeU7gY5peHdACa/UCRwqC/IB+Flamv9afKWAvRu5WpHKSCd04+Phq4A0Y1s9YRhqVFIy9xRWHdSMUX23HmeP/BXT+Z/BulZIcXjUWrmcFuVJY9lvRcQ4Vc1+7ERmPrk7Ckyl+3EEM3ARLOWgddH6rhOk1rnQE1avqxNK9PU3t9gvj1Tsm5vaRDix+o+VcICv8/DaglxAIs+eZZhgGkxY+7i9M/1y5Sr9qpNfTjEgZ7QfoGLZ8WcdxfUgY2rjm4r8C2BPx1P5lSy9H8xZ54NeQkK9aLUTGBtF5OL3Sa06ZbVuchxeygizzieZ/SRM2Qgx5ybTn8+sdGd4nfq1pHgf+Gh8aUqxbKDPiSF6WE7tspFNrdD4=

branches:
  only:
    - master
    - build

before_install:
  - export SUFFIX=$(git log -1 --format=%cd-%h --date=format:%Y%m%d-%H%M%S $TRAVIS_COMMIT)
  - export TIMESTAMP=$(git log -1 --format=%cd --date=format:%Y%m%d-%H%M%S $TRAVIS_COMMIT)
  - export RELEASE_NAME=b2-$SUFFIX
  - export OUTPUT_BASENAME=b2-osx-$SUFFIX.dmg
  - export OUTPUT_NAME=./build/_Rel/darwin/$OUTPUT_BASENAME
  - brew install ninja

before_deploy:
  # https://docs.travis-ci.com/user/deployment/releases/
  - git config --local user.name "Tom Seddon"
  - git config --local user.email "modelb@bbcmicro.com"
  - git tag $RELEASE_NAME

script: python ./etc/release/release.py --timestamp=$TIMESTAMP $SUFFIX

deploy:
  - provider: releases
    api_key:
      secure: r/uHB0E2ZQXdlakXeEISZdZD8K4WLkptyaYouPXG2xFLFZAgosuBkComk8uPkM4YH/qOo+7zHptELft8yO9uinil1IAWKmz6gxX6TrLQkdUWQThgRr0Vw5iLwymFr6MeESZ2G8jqc6CAw2YQJqhGhOU9AO5gvKfHFItrrVtoF+EOdRCd9w1wYUcH20uY0rGXD7vx6JmEpS1S48dDDr2XlAel368M1o3cjtaYo23uiW4K+21XMPCdK91Dz6fvnDXibnMTnOHmWGKIVp0lBow5R91a9ywHDmzNgyrEw+dmjAuMFtV3q05B8Wd5zg9zGAOt3dqkEdepvV+x9yqT1WXMg3t89x3gwKBPfrHIMPXDhDAg5iIDxi9L29XqvvZLExQIqQxDGQxRjAP2IinHfBsTBvBZAOA7gBVMDYppNTVOGU8FCxu3OGq9/CBlSQlgltZANDjboOexcc3abrNBhIvr0Fw7aE5YmCmwbIwmj+IQi2wmCsn1+o9jSACkm8h7k9mGuhw5LxvArZbu5W+Ka/wiTgXZnp3BcPaTMFLoMcoycY4DvweVLeALBg5esTbBsNbcxdHkOicwh8kwZIMCEes71WguXZV8fBoUsTn9GqzLY0MG3LQL7/RPobLBY+vdwrFb5zMEeuQCHu2uFXDUYbzfpTdE/ViXyUsqulajBbO5aGg=
    file: ${OUTPUT_NAME}
    skip_cleanup: true
    on:
      branch: build
  - provider: script
    script: ftp -u ftp://b2_upload:${FFE3_PASSWORD}@ffe3.com/ffe3.com/b2/ci/${OUTPUT_BASENAME} ${OUTPUT_NAME}
    on:
      branch: master
    skip_cleanup: true
