language: C++
sudo: false
os: osx
osx_image: xcode9.2

env:
  global:
  - secure: oXDczoOmtLRjBaLxa/SJfqE8R0kTCsDL0DAlReC0m4gl2pS8W65YWPBJvEtbzxUfE2kJZTFG2xnm17Lt4jxGiEu7th6hN0idWeNntrdJZrs5OCi8vivkGbe8YIjFgQclARKsEa+tXLJQmcpHHOLyk9Mf2Li9gZVwXpUDwRl8d5O330QdspjiElE3xcTveN+6BqHAQ5fu5LsCq9xx0ZPDJRq9I6Oegvu+YF6tl6KxFDNejUDv+b05M2Fe0EbHuCemaGpoox3aKvhVWClzr5mvnMBrfaW0TNs8k43g+Yv0MQpSd/qgOZ0RaQhtc4yFhxQI7rBGwVttOJAiCwdC/DVGQkiJnz1lOHgWqS+N3GNHPhemu/WgTaH/WTJE1u2xcyUK3LStRpwxtYTpEHA0USovpvoLRZ20y7ntUAUaCO8czpIDGk0ZsPBx26CbKTLnphmFKlNC45npEWoTsw6HYhekmlkLJmxEDFg98R3bp2PRnTPyKcAEsxD+uyAkp1mxFcOIP3v6wY50LVHIiaSt9QR5TlsaCb+VLvEzgcVbDIOc4R3ijHNDv6KLdgVcJ30RXtTIDkwiUNXSRpuQclIkM6QZeyfDOYOB/cjBY6MkfwfTbuYpeVWuhBq0iCvMhvr4HadQfrKjc5U8BD9R7ac8jWYHFlU/gRSir/wih450KUkH8ck=

branches:
  only:
    - master
    - build

before_install:
  - export SUFFIX=$(git log -1 --format=%cd-%h --date=format:%Y%m%d-%H%M%S $TRAVIS_COMMIT)
  - export RELEASE_NAME=b2-$SUFFIX
  - export OUTPUT_NAME=./build/_Rel/darwin/b2-osx-$SUFFIX.dmg
  - brew install ninja

before_deploy:
  # https://docs.travis-ci.com/user/deployment/releases/
  - git config --local user.name "Tom Seddon"
  - git config --local user.email "modelb@bbcmicro.com"
  - git tag $RELEASE_NAME

script: python ./etc/release/release.py $SUFFIX

deploy:
  - provider: releases
    api_key:
      secure: r/uHB0E2ZQXdlakXeEISZdZD8K4WLkptyaYouPXG2xFLFZAgosuBkComk8uPkM4YH/qOo+7zHptELft8yO9uinil1IAWKmz6gxX6TrLQkdUWQThgRr0Vw5iLwymFr6MeESZ2G8jqc6CAw2YQJqhGhOU9AO5gvKfHFItrrVtoF+EOdRCd9w1wYUcH20uY0rGXD7vx6JmEpS1S48dDDr2XlAel368M1o3cjtaYo23uiW4K+21XMPCdK91Dz6fvnDXibnMTnOHmWGKIVp0lBow5R91a9ywHDmzNgyrEw+dmjAuMFtV3q05B8Wd5zg9zGAOt3dqkEdepvV+x9yqT1WXMg3t89x3gwKBPfrHIMPXDhDAg5iIDxi9L29XqvvZLExQIqQxDGQxRjAP2IinHfBsTBvBZAOA7gBVMDYppNTVOGU8FCxu3OGq9/CBlSQlgltZANDjboOexcc3abrNBhIvr0Fw7aE5YmCmwbIwmj+IQi2wmCsn1+o9jSACkm8h7k9mGuhw5LxvArZbu5W+Ka/wiTgXZnp3BcPaTMFLoMcoycY4DvweVLeALBg5esTbBsNbcxdHkOicwh8kwZIMCEes71WguXZV8fBoUsTn9GqzLY0MG3LQL7/RPobLBY+vdwrFb5zMEeuQCHu2uFXDUYbzfpTdE/ViXyUsqulajBbO5aGg=
    file: ${OUTPUT_NAME}
    skip_cleanup: true
    on:
      branch: build
  - provider: script
    script: ftp -u ftp://b2_upload:${FFE3_PASSWORD}@ffe3.com/ffe3.com/b2/ci/${OUTPUT_NAME} ${OUTPUT_NAME}
    on:
      branch: master
    skip_cleanup: true
    
