version: '{build}'

# don't make Travis's tag creation prod AppVeyor into doing repeated
# builds.
skip_tags: true

branches:
  only:
    - master

image:
  - Visual Studio 2017
  # - Ubuntu1804
  # - macos-mojave

install:
  - ps: $env:SUFFIX = $(git log -1 --format=%cd-%h --date=format:%Y%m%d-%H%M%S $env:APPVEYOR_REPO_COMMIT)
  - ps: $env:TIMESTAMP = $(git log -1 --format=%cd --date=format:%Y%m%d-%H%M%S $env:APPVEYOR_REPO_COMMIT)
  - ps: $env:RELEASE_NAME = "b2-"+$env:SUFFIX
  - ps: |
      if ($env:CI_WINDOWS -eq $true) {
        echo 'Windows'
        $env:deploy=$true
        $env:OUTPUT_NAME="build/_Rel/win32/b2-windows-"+$env:SUFFIX+".zip"
      } elseif ($env:CI_LINUX -eq $true) {
        echo 'Linux'
        $env:deploy=$false
        sudo apt-get -y update
        sudo apt-get -y install libcurl4-openssl-dev libgl1-mesa-dev libglvnd-dev libgtk2.0-dev libpulse-dev uuid-dev
      } elseif ($env:CI_MACOS -eq $true) {
        echo 'macOS'
        $env:deploy=$true
        $env:OUTPUT_NAME="build/_Rel/osx/b2-osx-"+$env:SUFFIX+".dmg"
        $env:HOMEBREW_NO_AUTO_UPDATE=1
        $env:HOMEBREW_NO_INSTALL_CLEANUP=1
        brew install ninja
        brew install ffmpeg
        # brew install libav
        # which pkg-config
        # pkg-config --variable pc_path pkg-config
        # ls -l /usr/local/bin/
        # ls -l /usr/local/lib/
        # ls -l /usr/local/lib/pkgconfig/
        $env:PKG_CONFIG_PATH=$env:PKG_CONFIG_PATH+":/usr/local/lib/pkgconfig"
        pkg-config --libs libavcodec
      } else {
        echo 'Unknown platform'
        $env:PLATFORM=unknown
        $env:deploy=$false
      }
  - ps: 'dir env:'
  - git submodule init
  - git submodule update
  
build_script:
  - ps: $env:RELEASE_CMD=python -u ./etc/release/release.py --skip-debug --skip-32-bit --skip-ctest --verbose --timestamp=$env:TIMESTAMP $env:SUFFIX
  - ps: |
      if($env:CI_WINDOWS -ne $true) {
        $env:RELEASE_CMD
      }
  - cmd: %RELEASE_CMD%

artifacts:
  - path: $(OUTPUT_NAME)
    name: output

deploy:
  - release: $(RELEASE_NAME)
    description: 'b2'
    provider: GitHub
    auth_token:
      secure: NTWtNQsxaMVhAyad5bBM3H6lTGsqRCprICrq8kvYvXgjnaeDcjjLpNe0H0ZaG4sl
    artifact: output
    draft: false
    prerelease: false
    on:
      branch: master
      deploy: true
