version: '{build}'

branches:
  only:
    - master
    - build

image: Visual Studio 2015

install:
  - cmd: echo appveyor.yml install step
  - git submodule init
  - git submodule update
  
build_script:
  - python .\etc\release\release.py --ignore-branch --make .\snmake.exe

artifacts:
  - path: '.\build\_Rel\win32\b2-*.zip'

deploy:
  release: b2-$(appveyor_repo_commit)
  description: 'b2'
  provider: GitHub
  auth_token:
    secure: NTWtNQsxaMVhAyad5bBM3H6lTGsqRCprICrq8kvYvXgjnaeDcjjLpNe0H0ZaG4sl
  artifact: '.\build\_Rel\win32\b2-*.zip'
  draft: false
  prerelease: false
  on:
    branch: build
